spring.application.name=HotSauce
spring.datasource.url=jdbc:postgresql://localhost:5432/hot_sauce
spring.datasource.username=postgres
spring.datasource.password=Data1630$
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true